=== Hirlam/Harmonie.jl/harmonie.schema.json
{
  "$id": "https://roelstappers.github.io/harmonie.schema.json",
  "$schema" : "http://json-schema.org/schema#",
  "title": "Harmonie experiment configuration",
  "description" : "Look at the Surfex and Observations tabs for examples. See in Observations/LISTE_LOC obstype how enum_titles can be used to give meaningfull names to integers. See Geometry/domain how we can insert information directly in the config_exp.json (Click JSON. no need for perl). See surfex/Namelist how namelist can be included (no need for perl). ",
  "options": {
    "disable_properties": true,
    "disable_edit_json": false,
    "disable_collapse": true
  },
  "format": "categories",
  "type": "object",
  "required": [
    "Main",
    "Geometry",
    "Nesting",
    "Assimilation",
    "Physics",
    "Surfex",
    "Observations",
    "EPS",
    "Postprocessing",
    "Archiving",
    "Aux"
  ],
  "properties": {
    "Main": {
      "$ref": "schema/main/main.schema.json"
    },
    "Geometry": {
      "$ref": "schema/geometry/geometry.schema.json"
    },
    "Nesting": {
      "$ref": "schema/nesting/nesting.schema.json"
    },
    "Assimilation": {
      "$ref": "schema/assimilation/assimilation.schema.json"
    },
    "Physics": {
      "$ref": "schema/physics/physics.schema.json"
    },
    "Surfex": {
      "$ref": "schema/surfex/surfex.schema.json"
    },
    "Observations": {
      "$ref": "schema/observations/observations.schema.json"
    },
    "EPS": {
      "type": "object"
    },
    "Postprocessing": {
      "type": "object"
    },
    "Archiving": {
      "type": "object"
    },
    "Aux": {
      "$ref": "schema/aux/aux.schema.json"
    }
  }
}

=== Hirlam/Harmonie.jl/config_exp2.json
{
  "$schema": "./harmonie.schema.json",
  "Main": {
    "DTGBEG": "2007" ,
    "DTGEND": "",
    "GITURL": "https://github.com/roelstappers/hm_home/",
    "GITBRANCH": {
      "name": "cy43",
      "commit": {
        "sha": "571811786e682e586a9c732bc30cdde44448d9ba",
        "url": "https://api.github.com/repos/roelstappers/hm_home/commits/571811786e682e586a9c732bc30cdde44448d9ba"
      }
    },
    "PATHS": {
      "OBDIR": "$HMDATA/observations"
    },
    "MAIL_ON_ABORT": []
  },
  "Geometry": {
    "DOMAIN": {
      "NAME": "TRAINING_10",
      "TSTEP": 240,
      "NLON": 150,
      "NLAT": "150",
      "LONC": "14.8",
      "LATC": "51.9",
      "LON0": "20.0",
      "LAT0": "50.2",
      "GSIZE": "10000."
    },
    "TOPO_SOURCE": "gmted2010",
    "GRID_TYPE": "LINEAR",
    "VLEV": "65"
  },
  "Nesting": {
    "HOST_MODEL": "ifs",
    "HOST_SURFEX": "no",
    "SURFEX_INPUT_FORMAT": "lfi",
    "BDSTRATEGY": "simulate_operational",
    "BDINT": 1
  },
  "Assimilation": {
    "ANAATMO": "3DVAR",
    "LSMIXBC": "yes"
  },
  "Physics": {
    "PHYSICS": "arome",
    "HARATU": true,
    "MASS_FLUX_SCHEME": "edmfm"
  },
  "Surfex": {
    "CISBA": "3-L",
    "CSNOW": "3-L",
    "CROUGH": "NONE",
    "SURFEX_SEA_ICE": "none",
    "SURFEX_OUTPUT_FORMAT": "fa",
    "NPATCH": 1,
    "LISBA_CANOPY": ".TRUE.",
    "SURFEX_LAKES": "WATFLX",
    "MODIFY_LAKES": "F",
    "NAMELIST": {
      "NAM_TEB": {},
      "NAM_SSOn": {}
    }
  },
  "Observations": {
    "SYNOP_OBS": 1,
    "MODESEHS_OBS": 0,
    "AIRCRAFT_OBS": 1,
    "BOUY_OBS": 1,
    "TEMP_OBS": 1,
    "PILOT_OBS": 1,
    "GNSS_OBS": 0,
    "SGNSS_OBS": 0,
    "AMV_OBS": 0,
    "AMSUA_OBS": 0,
    "AMSUB_OBS": 0,
    "IASI_OBS": 0,
    "SEV_OBS": 0,
    "SEVIRI_OBS": 0,
    "SCATT_OBS": 0,
    "ATMS_OBS": 0,
    "CRIS_OBS": 0,
    "PAOB_OBS": 0,
    "LIMB_OBS": 0,
    "RADAR_OBS": 0,
    "LISTE_LOC": [ 
    

    ]
  },
  "EPS": {},
  "Postprocessing": {},
  "Archiving": {},
  "Aux": {
    "RUNNING_MODE": "research",
    "SIMULATION_TYPE": "nwp",
    "SINGLEOBS": "no",
    "USE_MSG": "no",
    "MSG_PATH": "$SCRATCH/CLOUDS",
    "Config": {
      "COMPCENTRE ": "LOCAL",
      "HM_DATA": "$HOME/scratch/hm_home/$EXP",
      "HM_LIB": "$HM_DATA/lib",
      "MAKEUP": "yes",
      "MAKE_OWN_PRECOMPILED": "no",
      "MAKEUP_BUILD_DIR": "$HM_LIB",
      "MAKEUP_BUILD_GRIB_API_FLAG": "-A",
      "HARMONIE_CONFIG": "linuxgfortran",
      "BUFR_TABLES": "$HM_LIB/util/auxlibs/bufr_405/bufrtables/",
      "GRIB_TEMPLATES_PATH": "$HM_LIB/util/grib_api/samples",
      "GRIB_SAMPLES_PATH": "$HM_LIB/util/grib_api/samples",
      "GRIB_DEFINITION_PATH": "$HM_LIB/util/gl_grib_api/definitions:$HM_LIB/util/grib_api/definitions",
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:${HM_LIB}/util/grib_api/fortran/.libs:${HM_LIB}/util/grib_api/src/.libs",
      "LMPOFF": ".TRUE.",
      "L_GATHERV_WRGP": ".FALSE.",
      "HM_CLDATA": "$HOME/climdata",
      "GMTED2010_INPUT_PATH": "$HM_CLDATA/GMTED",
      "PERL_TK": "perl",
      "PERLTKDIR": "",
      "ROOTPACK": "$HM_DATA/../rootpack",
      "GMKROOT": "$HM_LIB/util/gmkpack",
      "GMKFILE": "GFORTRAN.LINUX",
      "GMKTMP": "/tmp",
      "RSYNC_EXCLUDE": "'--exclude=.svn'",
      "HOST0": "`hostname`",
      "HOST_INSTALL": "0",
      "SMSHOST": "${SMSHOST-$HOST0}",
      "HM_COMDAT": "$HM_DATA/..",
      "PATH": ".:$HM_LIB/scr:$HM_LIB/msms:$HM_LIB:$GMKROOT/util:$PATH",
      "MAKE": "make",
      "MKDIR": "mkdir -p",
      "CDP": "${CDP-$HM_LIB/msms/sms_cdp}",
      "JOBOUTDIR": "$HM_DATA/sms_logfiles"
    },
    "hostdescriptions": {
      "HM_DATA0": "",
      "HM_LIB0": "",
      "HM_DATA1": "",
      "HM_LIB1": "",
      "DTGBEG": "",
      "DTGEND": "",
      "BUILD": "yes",
      "PLAYFILE": "harmonie"
    }
  }
}
